name: Test Merged Commits & Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout Codes
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Java17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.12'

      - name: Setup and Config Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver: docker-container
          buildkitd-flags: --debug

      - name: Build Spring Project
        run: |
          cd ./server/
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Print JAR Timestamp
        run: |
          ls -l ./server/build/libs/
    
      - name: Create Docker Image and Push Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --no-cache --platform linux/amd64 -t meteorfish/onetool-prod-server:v1.2 --push .
